FROM node:17

# set version to be installed
ARG IGV_VERSION=1.10.8

# install IGV app bundle
WORKDIR /
RUN wget "https://igv.org/app-archive/igv-webapp.${IGV_VERSION}.zip" && \
    unzip "igv-webapp.${IGV_VERSION}.zip" && \
    mv "igv-webapp.${IGV_VERSION}" igv

# add DNAnexus track resource
COPY test/hg19_dnanexus.json /igv/resources/tracks
COPY test/trackRegistry.json /igv/resources/tracks

# set working directory
WORKDIR /igv

# install http-server
RUN npm i -g http-server

# run app with simple http-server (NGINX should do the rest)
CMD ["http-server", "-a", "0.0.0.0", "-p", "8085"]
